package com.tuodao.bp.depository.db.mapper.basic;

import com.tuodao.bp.depository.db.model.basic.HttpReceiveLog;
import com.tuodao.bp.depository.db.model.basic.HttpReceiveLogWithBLOBs;

public interface HttpReceiveLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_receive_log
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_receive_log
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    int insert(HttpReceiveLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_receive_log
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    int insertSelective(HttpReceiveLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_receive_log
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    HttpReceiveLogWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_receive_log
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    int updateByPrimaryKeySelective(HttpReceiveLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_receive_log
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(HttpReceiveLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_receive_log
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    int updateByPrimaryKey(HttpReceiveLog record);
}