package com.tuodao.bp.depository.db.mapper.basic;

import com.tuodao.bp.depository.db.model.basic.HttpRequestLog;
import com.tuodao.bp.depository.db.model.basic.HttpRequestLogWithBLOBs;

public interface HttpRequestLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_request_log
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_request_log
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    int insert(HttpRequestLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_request_log
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    int insertSelective(HttpRequestLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_request_log
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    HttpRequestLogWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_request_log
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    int updateByPrimaryKeySelective(HttpRequestLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_request_log
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(HttpRequestLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_request_log
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    int updateByPrimaryKey(HttpRequestLog record);
}