package com.tuodao.bp.model.constant.depository.keyCouple;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import com.tuodao.bp.model.constant.depository.BJFN;
import com.tuodao.bp.model.constant.depository.TDFN;

public class KeyCouple {
	private static Map<String, String> bj2td0 = new HashMap<String, String>() {
		private static final long serialVersionUID = -2300675810053716587L;
		{
			/*put(BJFN.id, TDFN.id);
			put(BJFN.code, TDFN.code);
			put(BJFN.totalNum, TDFN.totalNum);
			put(BJFN.data, TDFN.data);
			put(BJFN.signdata, TDFN.signData);
			put(BJFN.platCust, TDFN.platCust);
			put(BJFN.type, TDFN.type);
			put(BJFN.idType, TDFN.idType);
			put(BJFN.idCode, TDFN.idCode);
			put(BJFN.name, TDFN.name);
			put(BJFN.cardNo, TDFN.cardNo);
			put(BJFN.cardType, TDFN.cardType);
			put(BJFN.preMobile, TDFN.premobile);
			put(BJFN.orgNo, TDFN.orgNo);
			put(BJFN.acctName, TDFN.acctName);
			put(BJFN.acctNo, TDFN.acctNo);
			put(BJFN.openBranch, TDFN.openBranch);
			put(BJFN.payCode, TDFN.payCode);
			put(BJFN.notifyUrl, TDFN.notifyUrl);
			put(BJFN.remark, TDFN.remark);
			put(BJFN.identifyingCode, TDFN.identifyingCode);
			put(BJFN.originOrderNo, TDFN.originOrderNo);
			put(BJFN.orderNo, TDFN.orderNo);
			put(BJFN.cusType, TDFN.cusType);			
			put(BJFN.mobile, TDFN.mobile);
			put(BJFN.email, TDFN.email);
			put(BJFN.prodId, TDFN.prodId);
			put(BJFN.prodName, TDFN.prodName);
			put(BJFN.prodType, TDFN.prodType);
			put(BJFN.totalLimit, TDFN.totalLimit);
			put(BJFN.valueType, TDFN.valueType);
			put(BJFN.createType, TDFN.createType);
			put(BJFN.sellDate, TDFN.sellDate);
			put(BJFN.valueDate, TDFN.valueDate);
			put(BJFN.expireDate, TDFN.expireDate);
			put(BJFN.cycle, TDFN.cycle);
			put(BJFN.cycleUnit, TDFN.cycleUnit);
			put(BJFN.istYear, TDFN.istYear);
			put(BJFN.repayType, TDFN.repayType);
			put(BJFN.financingInfoList, TDFN.financingInfoList);
			put(BJFN.riskLvl, TDFN.riskLvl);
			put(BJFN.prodInfo, TDFN.prodInfo);
			put(BJFN.buyerNumLimit, TDFN.buyerNumLimit);
			put(BJFN.chargeoffAuto, TDFN.chargeOffAuto);
			put(BJFN.overlimit, TDFN.overLimit);
			put(BJFN.overTotalLimit, TDFN.overTotalLimit);
			put(BJFN.compensation, TDFN.compensation);
			put(BJFN.flag, TDFN.flag);
			put(BJFN.funddata, TDFN.fundData);
			put(BJFN.repayPlanList, TDFN.repayPlanList);
			put(BJFN.chargeOffList, TDFN.chargeOffList);
			put(BJFN.transShare, TDFN.transShare);
			put(BJFN.transAmt, TDFN.transAmt);
			put(BJFN.dealAmount, TDFN.dealAmount);
			put(BJFN.couponAmt, TDFN.couponAmt);
			put(BJFN.dealPlatcust, TDFN.dealPlatcust);
			put(BJFN.commission, TDFN.commission);
			put(BJFN.commissionExt, TDFN.commissionExt);
			put(BJFN.publishDate, TDFN.publishDate);
			put(BJFN.transDate, TDFN.transDate);
			put(BJFN.transferIncome, TDFN.transferIncome);
			put(BJFN.incomeAcct, TDFN.incomeAcct);
			put(BJFN.relatedProdIds, TDFN.relatedProdIds);
			put(BJFN.subjectPriority, TDFN.subjectPriority);
			put(BJFN.repayNum, TDFN.repayNum);
			put(BJFN.isPayoff, TDFN.isPayoff);
			put(BJFN.withdrawAccount, TDFN.withdrawAccount);
			put(BJFN.accountType, TDFN.accountType);
			put(BJFN.payeeName, TDFN.payeeName);
			put(BJFN.detailNo, TDFN.detailNo);
			put(BJFN.experienceAmt, TDFN.experienceAmt);
			put(BJFN.selfAmt, TDFN.selfAmt);
			put(BJFN.inInterest, TDFN.inInterest);
			put(BJFN.custNo, TDFN.custNo);
			put(BJFN.regDate, TDFN.regDate);
			put(BJFN.regTime, TDFN.regTime);
			put(BJFN.financInt, TDFN.financInt);
			put(BJFN.financPurpose, TDFN.financPurpose);
			put(BJFN.financAmt, TDFN.financAmt);
			put(BJFN.useDate, TDFN.useDate);
			put(BJFN.feeInt, TDFN.feeInt);
			put(BJFN.payoutPlatType, TDFN.payoutPlatType);
			put(BJFN.repayAmt, TDFN.repayAmt);
			put(BJFN.repayFee, TDFN.repayFee);
			put(BJFN.repayDate, TDFN.repayDate);
			put(BJFN.isAdvance, TDFN.isAdvance);
			put(BJFN.outAmt, TDFN.outAmt);
			put(BJFN.clientProperty, TDFN.clientProperty);
			put(BJFN.cityCode, TDFN.cityCode);
			put(BJFN.repayFlag, TDFN.repayFlag);
			put(BJFN.realRepayAmount, TDFN.realRepayAmount);
			put(BJFN.ratesAmt, TDFN.ratesAmt);
			put(BJFN.realRepayVal, TDFN.realRepayVal);
			put(BJFN.realRepayDate, TDFN.realRepayDate);
			put(BJFN.realRepayAmt, TDFN.realRepayAmt);
			put(BJFN.amount, TDFN.amount);
			put(BJFN.freezeFlg, TDFN.freezeFlg);
			put(BJFN.freezeOrderNo, TDFN.freezeOrderNo);
			put(BJFN.sourceAccount, TDFN.sourceAccount);
			put(BJFN.amt, TDFN.amt);
			put(BJFN.destAccount, TDFN.destAccount);
			put(BJFN.causeType, TDFN.causeType);
			put(BJFN.orderAmt, TDFN.orderAmt);
			put(BJFN.transTime, TDFN.transTime);
			put(BJFN.payOrderNo, TDFN.payOrderNo);
			put(BJFN.payFinishDate, TDFN.payFinishDate);
			put(BJFN.orderStatus, TDFN.orderStatus);
			put(BJFN.payAmt, TDFN.payAmt);
			put(BJFN.errorInfo, TDFN.errorInfo);
			put(BJFN.errorNo, TDFN.errorNo);
			put(BJFN.hostReqSerialNo, TDFN.hostReqSerialNo);
			put(BJFN.chargeType, TDFN.chargeType);
			put(BJFN.currencyCode, TDFN.currencyCode);
			put(BJFN.returnUrl, TDFN.returnUrl);
			put(BJFN.bankcode, TDFN.bankcode);
			put(BJFN.bankId, TDFN.bankId);
			put(BJFN.branchFlag, TDFN.branchFlag);
			put(BJFN.platAccount, TDFN.platAccount);
			put(BJFN.sex, TDFN.sex);
			put(BJFN.birthday, TDFN.birthday);
			put(BJFN.orgName, TDFN.orgName);
			put(BJFN.businessLicense, TDFN.businessLicense);
			put(BJFN.bankLicense, TDFN.bankLicense);
			put(BJFN.cardNoOld, TDFN.cardNoOld);
			put(BJFN.cardTypeOld, TDFN.cardTypeOld);
			put(BJFN.payFinishTime, TDFN.payFinishTime);
			put(BJFN.feeAmt, TDFN.feeAmt);
			put(BJFN.withdrawType, TDFN.withdrawType);
			put(BJFN.pagesize, TDFN.pageSize);
			put(BJFN.pagenum, TDFN.pageNum);
			put(BJFN.startDate, TDFN.startDate);
			put(BJFN.endDate, TDFN.endDate);
			put(BJFN.transName, TDFN.transName);
			put(BJFN.account, TDFN.account);
			put(BJFN.acctType, TDFN.acctType);
			put(BJFN.fundType, TDFN.fundType);
			put(BJFN.queryOrderNo, TDFN.queryOrderNo);
			put(BJFN.originalSerialNo, TDFN.originalSerialNo);
			put(BJFN.occurBalance, TDFN.occurBalance);
			put(BJFN.compensationPlatcust, TDFN.compensationPlatCust);
			put(BJFN.platcustlist, TDFN.platcustList);
			put(BJFN.bankNo, TDFN.bankNo);
			put(BJFN.processDate, TDFN.processDate);
			put(BJFN.queryId, TDFN.queryId);
			put(BJFN.amtType, TDFN.amtType);
			put(BJFN.paycheckDate, TDFN.paycheckDate);
			put(BJFN.precheckFlag, TDFN.precheckFlag);
			put(BJFN.requestUrl, TDFN.requestUrl);
			put(BJFN.platNo, TDFN.platNo);
			put(BJFN.partnerTransDate, TDFN.partnerTransDate);
			put(BJFN.partnerTransTime, TDFN.partnerTransTime);
			put(BJFN.payoutAmt, TDFN.payoutAmt);
			put(BJFN.recode, TDFN.recode);
			put(BJFN.remsg, TDFN.remsg);			
			put(BJFN.finishDatetime, TDFN.finishDateTime);
			put(BJFN.successNum, TDFN.successNum);
			put(BJFN.successData, TDFN.successData);
			put(BJFN.errorData, TDFN.errorData);
			put(BJFN.success, TDFN.success);
			put(BJFN.error, TDFN.error);
			put(BJFN.orderInfo, TDFN.orderInfo);
			put(BJFN.balance, TDFN.balance);*/

		}
	};

	public static final Map<String, String> bj2td = Collections.unmodifiableMap(bj2td0);

	private static Map<String, String> td2bj0 = new HashMap<String, String>() {
		private static final long serialVersionUID = -589299495301900875L;
		{
			/*put(TDFN.id,BJFN.id);
			put(TDFN.code,BJFN.code);
			put(TDFN.totalNum,BJFN.totalNum);
			put(TDFN.data,BJFN.data);
			put(TDFN.signData,BJFN.signdata);
			put(TDFN.platCust,BJFN.platCust);
			put(TDFN.type,BJFN.type);
			put(TDFN.idType,BJFN.idType);
			put(TDFN.idCode,BJFN.idCode);
			put(TDFN.name,BJFN.name);
			put(TDFN.cardNo,BJFN.cardNo);
			put(TDFN.cardType,BJFN.cardType);
			put(TDFN.premobile,BJFN.preMobile);
			put(TDFN.orgNo,BJFN.orgNo);
			put(TDFN.acctName,BJFN.acctName);
			put(TDFN.acctNo,BJFN.acctNo);
			put(TDFN.openBranch,BJFN.openBranch);
			put(TDFN.payCode,BJFN.payCode);
			put(TDFN.notifyUrl,BJFN.notifyUrl);
			put(TDFN.remark,BJFN.remark);
			put(TDFN.identifyingCode,BJFN.identifyingCode);
			put(TDFN.originOrderNo,BJFN.originOrderNo);
			put(TDFN.orderNo,BJFN.orderNo);
			put(TDFN.cusType,BJFN.cusType);
			put(TDFN.mobile,BJFN.mobile);
			put(TDFN.email,BJFN.email);
			put(TDFN.prodId,BJFN.prodId);
			put(TDFN.prodName,BJFN.prodName);
			put(TDFN.prodType,BJFN.prodType);
			put(TDFN.totalLimit,BJFN.totalLimit);
			put(TDFN.valueType,BJFN.valueType);
			put(TDFN.createType,BJFN.createType);
			put(TDFN.sellDate,BJFN.sellDate);
			put(TDFN.valueDate,BJFN.valueDate);
			put(TDFN.expireDate,BJFN.expireDate);
			put(TDFN.cycle,BJFN.cycle);
			put(TDFN.cycleUnit,BJFN.cycleUnit);
			put(TDFN.istYear,BJFN.istYear);
			put(TDFN.repayType,BJFN.repayType);
			put(TDFN.financingInfoList,BJFN.financingInfoList);
			put(TDFN.riskLvl,BJFN.riskLvl);
			put(TDFN.prodInfo,BJFN.prodInfo);
			put(TDFN.buyerNumLimit,BJFN.buyerNumLimit);
			put(TDFN.chargeOffAuto,BJFN.chargeoffAuto);
			put(TDFN.overLimit,BJFN.overlimit);
			put(TDFN.overTotalLimit,BJFN.overTotalLimit);
			put(TDFN.compensation,BJFN.compensation);
			put(TDFN.flag,BJFN.flag);
			put(TDFN.fundData,BJFN.funddata);
			put(TDFN.repayPlanList,BJFN.repayPlanList);
			put(TDFN.chargeOffList,BJFN.chargeOffList);
			put(TDFN.transShare,BJFN.transShare);
			put(TDFN.transAmt,BJFN.transAmt);
			put(TDFN.dealAmount,BJFN.dealAmount);
			put(TDFN.couponAmt,BJFN.couponAmt);
			put(TDFN.dealPlatcust,BJFN.dealPlatcust);
			put(TDFN.commission,BJFN.commission);
			put(TDFN.commissionExt,BJFN.commissionExt);
			put(TDFN.publishDate,BJFN.publishDate);
			put(TDFN.transDate,BJFN.transDate);
			put(TDFN.transferIncome,BJFN.transferIncome);
			put(TDFN.incomeAcct,BJFN.incomeAcct);
			put(TDFN.relatedProdIds,BJFN.relatedProdIds);
			put(TDFN.subjectPriority,BJFN.subjectPriority);
			put(TDFN.repayNum,BJFN.repayNum);
			put(TDFN.isPayoff,BJFN.isPayoff);
			put(TDFN.withdrawAccount,BJFN.withdrawAccount);
			put(TDFN.accountType,BJFN.accountType);
			put(TDFN.payeeName,BJFN.payeeName);
			put(TDFN.detailNo,BJFN.detailNo);
			put(TDFN.experienceAmt,BJFN.experienceAmt);
			put(TDFN.selfAmt,BJFN.selfAmt);
			put(TDFN.inInterest,BJFN.inInterest);
			put(TDFN.custNo,BJFN.custNo);
			put(TDFN.regDate,BJFN.regDate);
			put(TDFN.regTime,BJFN.regTime);
			put(TDFN.financInt,BJFN.financInt);
			put(TDFN.financPurpose,BJFN.financPurpose);
			put(TDFN.financAmt,BJFN.financAmt);
			put(TDFN.useDate,BJFN.useDate);
			put(TDFN.feeInt,BJFN.feeInt);
			put(TDFN.payoutPlatType,BJFN.payoutPlatType);
			put(TDFN.repayAmt,BJFN.repayAmt);
			put(TDFN.repayFee,BJFN.repayFee);
			put(TDFN.repayDate,BJFN.repayDate);
			put(TDFN.isAdvance,BJFN.isAdvance);
			put(TDFN.outAmt,BJFN.outAmt);
			put(TDFN.clientProperty,BJFN.clientProperty);
			put(TDFN.cityCode,BJFN.cityCode);
			put(TDFN.repayFlag,BJFN.repayFlag);
			put(TDFN.realRepayAmount,BJFN.realRepayAmount);
			put(TDFN.ratesAmt,BJFN.ratesAmt);
			put(TDFN.realRepayVal,BJFN.realRepayVal);
			put(TDFN.realRepayDate,BJFN.realRepayDate);
			put(TDFN.realRepayAmt,BJFN.realRepayAmt);
			put(TDFN.amount,BJFN.amount);
			put(TDFN.freezeFlg,BJFN.freezeFlg);
			put(TDFN.freezeOrderNo,BJFN.freezeOrderNo);
			put(TDFN.sourceAccount,BJFN.sourceAccount);
			put(TDFN.amt,BJFN.amt);
			put(TDFN.destAccount,BJFN.destAccount);
			put(TDFN.causeType,BJFN.causeType);
			put(TDFN.orderAmt,BJFN.orderAmt);
			put(TDFN.transTime,BJFN.transTime);
			put(TDFN.payOrderNo,BJFN.payOrderNo);
			put(TDFN.payFinishDate,BJFN.payFinishDate);
			put(TDFN.orderStatus,BJFN.orderStatus);
			put(TDFN.payAmt,BJFN.payAmt);
			put(TDFN.errorInfo,BJFN.errorInfo);
			put(TDFN.errorNo,BJFN.errorNo);
			put(TDFN.hostReqSerialNo,BJFN.hostReqSerialNo);
			put(TDFN.chargeType,BJFN.chargeType);
			put(TDFN.currencyCode,BJFN.currencyCode);
			put(TDFN.returnUrl,BJFN.returnUrl);
			put(TDFN.bankcode,BJFN.bankcode);
			put(TDFN.bankId,BJFN.bankId);
			put(TDFN.branchFlag,BJFN.branchFlag);
			put(TDFN.platAccount,BJFN.platAccount);
			put(TDFN.sex,BJFN.sex);
			put(TDFN.birthday,BJFN.birthday);
			put(TDFN.orgName,BJFN.orgName);
			put(TDFN.businessLicense,BJFN.businessLicense);
			put(TDFN.bankLicense,BJFN.bankLicense);
			put(TDFN.cardNoOld,BJFN.cardNoOld);
			put(TDFN.cardTypeOld,BJFN.cardTypeOld);
			put(TDFN.payFinishTime,BJFN.payFinishTime);
			put(TDFN.feeAmt,BJFN.feeAmt);
			put(TDFN.withdrawType,BJFN.withdrawType);
			put(TDFN.pageSize,BJFN.pagesize);
			put(TDFN.pageNum,BJFN.pagenum);
			put(TDFN.startDate,BJFN.startDate);
			put(TDFN.endDate,BJFN.endDate);
			put(TDFN.transName,BJFN.transName);
			put(TDFN.account,BJFN.account);
			put(TDFN.acctType,BJFN.acctType);
			put(TDFN.fundType,BJFN.fundType);
			put(TDFN.queryOrderNo,BJFN.queryOrderNo);
			put(TDFN.originalSerialNo,BJFN.originalSerialNo);
			put(TDFN.occurBalance,BJFN.occurBalance);
			put(TDFN.compensationPlatCust,BJFN.compensationPlatcust);
			put(TDFN.platcustList,BJFN.platcustlist);
			put(TDFN.bankNo,BJFN.bankNo);
			put(TDFN.processDate,BJFN.processDate);
			put(TDFN.queryId,BJFN.queryId);
			put(TDFN.amtType,BJFN.amtType);
			put(TDFN.paycheckDate,BJFN.paycheckDate);
			put(TDFN.precheckFlag,BJFN.precheckFlag);
			put(TDFN.requestUrl,BJFN.requestUrl);
			put(TDFN.platNo,BJFN.platNo);
			put(TDFN.partnerTransDate,BJFN.partnerTransDate);
			put(TDFN.partnerTransTime,BJFN.partnerTransTime);
			put(TDFN.payoutAmt,BJFN.payoutAmt);
			put(TDFN.recode,BJFN.recode);
			put(TDFN.remsg,BJFN.remsg);
			put(TDFN.finishDateTime,BJFN.finishDatetime);
			put(TDFN.successNum,BJFN.successNum);
			put(TDFN.successData,BJFN.successData);
			put(TDFN.errorData,BJFN.errorData);
			put(TDFN.success,BJFN.success);
			put(TDFN.error,BJFN.error);
			put(TDFN.orderInfo,BJFN.orderInfo);
			put(TDFN.balance, BJFN.balance);*/
		}
	};

	public static final Map<String, String> td2bj = Collections.unmodifiableMap(td2bj0);

}
