package com.tuodao.bp.depository.db.model.basic;

import java.util.Date;
import java.util.HashMap;

import com.tuodao.bp.model.depository.BaseMap;

public class HttpRequestLog extends BaseMap {

	public HttpRequestLog() {
	}

	public HttpRequestLog(HashMap<String, String> map) {
		super(map);

	}

	private static final long serialVersionUID = -3595887779866358911L;

	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column http_request_log.request_time
	 *
	 * @mbg.generated Tue Sep 26 15:58:40 CST 2017
	 */
	private Date requestTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column http_request_log.response_time
	 *
	 * @mbg.generated Tue Sep 26 15:58:40 CST 2017
	 */
	private Date responseTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column http_request_log.local_error
	 *
	 * @mbg.generated Tue Sep 26 15:58:40 CST 2017
	 */
	private String localError;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column http_request_log.id
	 *
	 * @return the value of http_request_log.id
	 *
	 * @mbg.generated Tue Sep 26 15:58:40 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column http_request_log.id
	 *
	 * @param id
	 *            the value for http_request_log.id
	 *
	 * @mbg.generated Tue Sep 26 15:58:40 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id == null ? null : id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column http_request_log.request_time
	 *
	 * @return the value of http_request_log.request_time
	 *
	 * @mbg.generated Tue Sep 26 15:58:40 CST 2017
	 */
	public Date getRequestTime() {
		return requestTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column http_request_log.request_time
	 *
	 * @param requestTime
	 *            the value for http_request_log.request_time
	 *
	 * @mbg.generated Tue Sep 26 15:58:40 CST 2017
	 */
	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column http_request_log.response_time
	 *
	 * @return the value of http_request_log.response_time
	 *
	 * @mbg.generated Tue Sep 26 15:58:40 CST 2017
	 */
	public Date getResponseTime() {
		return responseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column http_request_log.response_time
	 *
	 * @param responseTime
	 *            the value for http_request_log.response_time
	 *
	 * @mbg.generated Tue Sep 26 15:58:40 CST 2017
	 */
	public void setResponseTime(Date responseTime) {
		this.responseTime = responseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column http_request_log.local_error
	 *
	 * @return the value of http_request_log.local_error
	 *
	 * @mbg.generated Tue Sep 26 15:58:40 CST 2017
	 */
	public String getLocalError() {
		return localError;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column http_request_log.local_error
	 *
	 * @param localError
	 *            the value for http_request_log.local_error
	 *
	 * @mbg.generated Tue Sep 26 15:58:40 CST 2017
	 */
	public void setLocalError(String localError) {
		this.localError = localError == null ? null : localError.trim();
	}
	

	private String orderNo;

	public String getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

}