package com.tuodao.bp.depository.db.model.basic;

import java.util.Date;
import java.util.HashMap;

import com.tuodao.bp.model.depository.BaseMap;

public class HttpReceiveLog extends BaseMap {
	
	
	
    private static final long serialVersionUID = -5837285428781121080L;

	public HttpReceiveLog() {
		super();
	}

	public HttpReceiveLog(HashMap<String, String> map) {
		super(map);
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_receive_log.id
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_receive_log.order_id
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_receive_log.receive_time
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    private Date receiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_receive_log.receive_ip
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    private String receiveIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_receive_log.receive_method
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    private String receiveMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_receive_log.response_time
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    private Date responseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_receive_log.local_error
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    private String localError;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_receive_log.id
     *
     * @return the value of http_receive_log.id
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_receive_log.id
     *
     * @param id the value for http_receive_log.id
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_receive_log.order_id
     *
     * @return the value of http_receive_log.order_id
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_receive_log.order_id
     *
     * @param orderId the value for http_receive_log.order_id
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_receive_log.receive_time
     *
     * @return the value of http_receive_log.receive_time
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_receive_log.receive_time
     *
     * @param receiveTime the value for http_receive_log.receive_time
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_receive_log.receive_ip
     *
     * @return the value of http_receive_log.receive_ip
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public String getReceiveIp() {
        return receiveIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_receive_log.receive_ip
     *
     * @param receiveIp the value for http_receive_log.receive_ip
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public void setReceiveIp(String receiveIp) {
        this.receiveIp = receiveIp == null ? null : receiveIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_receive_log.receive_method
     *
     * @return the value of http_receive_log.receive_method
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public String getReceiveMethod() {
        return receiveMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_receive_log.receive_method
     *
     * @param receiveMethod the value for http_receive_log.receive_method
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public void setReceiveMethod(String receiveMethod) {
        this.receiveMethod = receiveMethod == null ? null : receiveMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_receive_log.response_time
     *
     * @return the value of http_receive_log.response_time
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public Date getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_receive_log.response_time
     *
     * @param responseTime the value for http_receive_log.response_time
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public void setResponseTime(Date responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_receive_log.local_error
     *
     * @return the value of http_receive_log.local_error
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public String getLocalError() {
        return localError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_receive_log.local_error
     *
     * @param localError the value for http_receive_log.local_error
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public void setLocalError(String localError) {
        this.localError = localError == null ? null : localError.trim();
    }

	
}