package com.tuodao.bp.depository.db.model.basic;

import java.util.HashMap;

public class HttpReceiveLogWithBLOBs extends HttpReceiveLog {
    
	
	public HttpReceiveLogWithBLOBs() {
		super();
	}

	public HttpReceiveLogWithBLOBs(HashMap<String, String> map) {
		super(map);
	}

	
	private static final long serialVersionUID = -7109620505883906509L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_receive_log.receive_url
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    private String receiveUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_receive_log.receive_para
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    private String receivePara;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_receive_log.response_content
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    private String responseContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_receive_log.receive_url
     *
     * @return the value of http_receive_log.receive_url
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public String getReceiveUrl() {
        return receiveUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_receive_log.receive_url
     *
     * @param receiveUrl the value for http_receive_log.receive_url
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public void setReceiveUrl(String receiveUrl) {
        this.receiveUrl = receiveUrl == null ? null : receiveUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_receive_log.receive_para
     *
     * @return the value of http_receive_log.receive_para
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public String getReceivePara() {
        return receivePara;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_receive_log.receive_para
     *
     * @param receivePara the value for http_receive_log.receive_para
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public void setReceivePara(String receivePara) {
        this.receivePara = receivePara == null ? null : receivePara.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_receive_log.response_content
     *
     * @return the value of http_receive_log.response_content
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public String getResponseContent() {
        return responseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_receive_log.response_content
     *
     * @param responseContent the value for http_receive_log.response_content
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public void setResponseContent(String responseContent) {
        this.responseContent = responseContent == null ? null : responseContent.trim();
    }
}