package com.tuodao.bp.depository.db.model.basic;

import java.util.HashMap;

public class HttpRequestLogWithBLOBs extends HttpRequestLog {
    
	public HttpRequestLogWithBLOBs() {
		super();
	}

	public HttpRequestLogWithBLOBs(HashMap<String, String> map) {
		super(map);
	}
	private static final long serialVersionUID = -788648892896853298L;
	

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_request_log.request_url
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    private String requestUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_request_log.response_content
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    private String responseContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_request_log.request_url
     *
     * @return the value of http_request_log.request_url
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_request_log.request_url
     *
     * @param requestUrl the value for http_request_log.request_url
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl == null ? null : requestUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_request_log.response_content
     *
     * @return the value of http_request_log.response_content
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public String getResponseContent() {
        return responseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_request_log.response_content
     *
     * @param responseContent the value for http_request_log.response_content
     *
     * @mbg.generated Tue Sep 26 15:58:40 CST 2017
     */
    public void setResponseContent(String responseContent) {
        this.responseContent = responseContent == null ? null : responseContent.trim();
    }
    
   
    
}